version: '3.7'
services:
  front:
    image: node
    volumes:
      - ./front-end:/app
    working_dir: /app
    command: "npm start -- --host=0.0.0.0 --port 4200"
    ports: 
      - 4200:4200
    environment:
      API_URL: "http://web-mkt:3000"

  web-mkt:
    image: node
    volumes:
      - ./mkt-node:/app
    working_dir: /app
    command: "npm start"
    environment: 
      SERVER_PORT: 3000
      MONGO_URL: "mongodb://mkt-usuario:mkt-senha@mongo-mkt:27017/mkt?authSource=admin"
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    ports:
      - 3000:3000

  mongo-mkt:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mkt-usuario
      MONGO_INITDB_ROOT_PASSWORD: mkt-senha
      MONGO_INITDB_DATABASE: mkt

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672

  web-financeiro:
    build: ./financeiro-php
    command: php index.php
    ports:
      - 9501:9501
    volumes:
      - ./financeiro-php:/app
    working_dir: /app

  api-gateway:
    image: nginx
    volumes:
      - ./servicos-nginx:/etc/nginx/conf.d
    restart: always
    ports:
      - 80:80

  consumer-academico:
    build: ./academico-php
    volumes:
      - ./academico-php:/app
    working_dir: /app
    command: php receive.php
    depends_on:
      - rabbitmq
      - postgre-academico
    environment:
      DB_DSN: pgsql:host=postgre-academico;dbname=academico;port=5432
      DB_USERNAME: usuario_academico
      DB_PASSWORD: senhapg
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest

  postgre-academico:
    image: postgres
    environment:
      POSTGRES_PASSWORD: senhapg
      POSTGRES_USER: usuario_academico
      POSTGRES_DB: academico

  web-academico:
    build: ./academico-php-web
    environment:
      JWT_KEY: chave-jwt
      DB_CONNECTION: pgsql
      DB_HOST: postgre-academico
      DB_DATABASE: academico
      DB_USERNAME: usuario_academico
      DB_PASSWORD: senhapg
      APP_KEY: c08cbbfd6eefc83ac6d23c4c791277e4
      APP_URL: http://web-academico:8080
    volumes:
      - ./academico-php-web/:/app
    working_dir: /app
    command: bash -c "php artisan migrate --force && php -S web-academico:8080 -t public"
    ports:
      - 8080:8080
    depends_on:
      - postgre-academico
